/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-primary-container": "#dad7ff",
        "primary": "#3525cd",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed-variant": "#005236",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#d3e4fe",
        "tertiary-container": "#885500",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-tint": "#4d44e3",
        "on-error": "#ffffff",
        "secondary": "#006c49",
        "on-primary-fixed-variant": "#3323cc",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#0f0069",
        "tertiary": "#684000",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "outline": "#777587",
        "on-background": "#0b1c30",
        "on-tertiary-container": "#ffd4a4",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed-variant": "#653e00",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#e2dfff",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#c3c0ff",
        "on-secondary-container": "#00714d",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#6cf8bb",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-low": "#eff4ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding-desktop": "32px",
        "sidebar-collapsed-width": "80px",
        "topbar-height": "72px",
        "container-padding-mobile": "16px",
        "base": "8px",
        "sidebar-width": "280px",
        "gutter": "24px"
      },
      fontFamily: {
        "be-vietnam": ["Be Vietnam Pro", "sans-serif"],
      }
    },
  },
  plugins: [],
}
