services:
  backend_SYSTEM:
    build:
      context: ./BE_SYSTEM
      dockerfile: Dockerfile
    image: ghcr.io/mnhwuanz/demo_hethongdiemdanh-backend:latest
    container_name: app_backend_system
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@app_mysql:3306/${MYSQL_DATABASE}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
    networks:
      - default
      - shared_db
  frontend_SYSTEM:
    build:
      context: ./FE_SYSTEM
      dockerfile: Dockerfile
    image: ghcr.io/mnhwuanz/demo_hethongdiemdanh-frontend:latest
    container_name: app_frontend_system
    restart: unless-stopped
    depends_on:
      - backend_SYSTEM
  cloudflared_SYSTEM:
    image: cloudflare/cloudflared:latest
    container_name: app_cloudflared_system
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - frontend_SYSTEM
networks:
  shared_db:
    external: true
